<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" >

    <xacro:include filename="inertial_macros.xacro"/>

    <xacro:property name="wheel_radius" value="0.095"/>
    <xacro:property name="wheel_thickness" value="0.05"/>
    <xacro:property name="wheel_mass" value="0.05"/>
    <xacro:property name="wheel_offset_x" value="0.2875"/>
    <xacro:property name="wheel_offset_y" value="0.1875"/>
    <xacro:property name="wheel_offset_z" value="0.095"/>
    <xacro:property name="caster_wheel_radius" value="0.06"/>
    <xacro:property name="caster_wheel_thickness" value="0.05"/>
    <xacro:property name="caster_wheel_mass" value="0.01"/>
    <xacro:property name="caster_wheel_offset_x" value="0.2875"/>
    <xacro:property name="caster_wheel_offset_z" value="${wheel_offset_z - wheel_radius + caster_wheel_radius}"/>

    <!-- BASE LINK -->

    <link name="base_link">

    </link>

    <!-- BASE_FOOTPRINT LINK -->

    <joint name="base_footprint_joint" type="fixed">
        <parent link="base_link"/>
        <child link="base_footprint"/>
        <origin xyz="0 0 0" rpy="0 0 0"/>
    </joint>
    
    <link name="base_footprint">
    </link>

    <!-- CHASSIS LINK -->
    <joint name="base_joint" type="fixed">
        <parent link="base_link"/>
        <child link="base_plate"/>
        <origin xyz="${-(wheel_offset_x)/2-0.04} 0 ${wheel_offset_z}"/>
    </joint>

    <link name="base_plate">
        <visual>
            <geometry>
                <box size="0.34 .28 .05" />
            </geometry>
            <origin rpy="0 0 0" xyz="0 0 0.025" />
            <material name="black">
                <color rgba="0 0 0 1" />
            </material>
        </visual>
        <collision>
            <origin xyz="0 0 .025"/>
            <geometry>
                <box size="0.34 0.28 0.05"/>
            </geometry>
        </collision>
        <xacro:inertial_box mass="0.5" x="0.34" y="0.28" z="0.05">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_box>
    </link>

    <joint name="front_beam_joint" type="fixed">
        <parent link="base_plate"/>
        <child link="front_beam"/>
        <origin xyz="${wheel_offset_x/2+0.04} 0 ${-0.025}"/>
    </joint>

    <link name="front_beam">
        <visual>
            <geometry>
                <box size="0.04 .34 .04" />
            </geometry>
            <origin rpy="0 0 0" xyz="0 0 0.025" />
            <material name="black">
                <color rgba="0 0 0 1" />
            </material>
        </visual>
        <collision>
            <origin xyz="0 0 .025"/>
            <geometry>
                <box size="0.04 0.34 0.04"/>
            </geometry>
        </collision>
        <xacro:inertial_box mass="0.5" x="0.04" y="0.34" z="0.04">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_box>
    </link>

    <gazebo reference="front_beam">
        <material>Gazebo/Black</material>
    </gazebo>

    <joint name="base_to_second_layercylinder_1" type="fixed">
        <parent link="base_plate"/>
        <child link="second_layercylinder_1"/>
        <origin xyz="0.165 0.14 0.025"/>
    </joint>

    <link name="second_layercylinder_1">
        <visual>
            <geometry>
                <cylinder length="0.25" radius="0.005" />
            </geometry>
            <origin xyz="0 0 0.125" rpy="0 0 0"/>
            <material name="gold">
                <color rgba="1 0.549 0 1.0" />
            </material>
        </visual>
    </link>
    
    <joint name="base_to_second_layercylinder_2" type="fixed">
        <parent link="base_plate"/>
        <child link="second_layercylinder_2"/>
        <origin xyz="-0.165 0.14 0.025"/>
    </joint>

    <link name="second_layercylinder_2">
        <visual>
            <geometry>
                <cylinder length="0.25" radius="0.005" />
            </geometry>
            <origin rpy="0 0 0" xyz="0 0 0.125" />
            <material name="gold"/>
        </visual>
    </link>

    <joint name="base_to_second_layercylinder_3" type="fixed">
        <parent link="base_plate"/>
        <child link="second_layercylinder_3"/>
        <origin xyz="-0.165 -0.14 0.025"/>
    </joint>    

    <link name="second_layercylinder_3">
        <visual>
            <geometry>
                <cylinder length="0.25" radius="0.005" />
            </geometry>
            <origin rpy="0 0 0" xyz="0 0 0.125" />
            <material name="gold"/>  
        </visual>
    </link>

    <joint name="base_to_second_layercylinder_4" type="fixed">
        <parent link="base_plate"/>
        <child link="second_layercylinder_4"/>
        <origin xyz="0.165 -0.14 0.025"/>
    </joint>

    <link name="second_layercylinder_4">
        <visual>
            <geometry>
                <cylinder length="0.25" radius="0.005" />
            </geometry>
            <origin rpy="0 0 0" xyz="0 0 0.125" />
            <material name="gold"/>
        </visual>
    </link>

    <!-- LEFT WHEEL LINK -->

    <joint name="left_wheel_joint" type="continuous">
        <parent link="base_link"/>
        <child link="left_wheel"/>
        <origin xyz="0 ${wheel_offset_y} ${wheel_offset_z}" rpy="-${pi/2} 0 0" />
        <axis xyz="0 0 1"/>
    </joint>

    <link name="left_wheel">
        <visual>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_thickness}"/>
            </geometry>
            <material name="cyan">
                <color rgba="0 1 1 1" />
            </material>
        </visual>
        <collision>
            <geometry>
                <sphere radius="${wheel_radius}"/>
            </geometry>
        </collision>
        <xacro:inertial_cylinder mass="${wheel_mass}" length="${wheel_thickness}" radius="${wheel_radius}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_cylinder>
    </link>

    <gazebo reference="left_wheel">
        <material>Gazebo/Blue</material>
    </gazebo>

    <!-- RIGHT WHEEL LINK -->

    <joint name="right_wheel_joint" type="continuous">
        <parent link="base_link"/>
        <child link="right_wheel"/>
        <origin xyz="0 ${-wheel_offset_y} ${wheel_offset_z}" rpy="${pi/2} 0 0" />
        <axis xyz="0 0 -1"/>
    </joint>

    <link name="right_wheel">
        <visual>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_thickness}"/>
            </geometry>
            <material name="cyan">
                <color rgba="0 1 1 1" />
            </material>
        </visual>
        <collision>
            <geometry>
                <sphere radius="${wheel_radius}"/>
            </geometry>
        </collision>
        <xacro:inertial_cylinder mass="${wheel_mass}" length="${wheel_thickness}" radius="${wheel_radius}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_cylinder>
    </link>

    <gazebo reference="right_wheel">
        <material>Gazebo/Blue</material>
    </gazebo>

    <!-- CASTER WHEEL LINK -->

    <joint name="left_caster_wheel_joint" type="continuous">
        <parent link="base_link"/>
        <child link="left_caster_wheel"/>
        <origin xyz="${-caster_wheel_offset_x} ${wheel_offset_y} ${caster_wheel_offset_z}" rpy="${pi/2} 0 0" />
        <axis xyz="0 0 1"/>
    </joint>


    <link name="left_caster_wheel">
        <visual>
            <geometry>
                <cylinder radius="${caster_wheel_radius}" length="${caster_wheel_thickness}"/>
            </geometry>
            <material name="white">
                <color rgba="1 1 1 1" />
            </material>
        </visual>
        <collision>
            <geometry>
                <sphere radius="${caster_wheel_radius}"/>
            </geometry>
        </collision>
        <xacro:inertial_cylinder mass="${caster_wheel_mass}" length="${caster_wheel_thickness}" radius="${caster_wheel_radius}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_cylinder>
    </link>

    <gazebo reference="left_caster_wheel">
        <material>Gazebo/White</material>
        <mu1 value="0.001"/>
        <mu2 value="0.001"/>
    </gazebo>

    <joint name="right_caster_wheel_joint" type="continuous">
        <parent link="base_link"/>
        <child link="right_caster_wheel"/>
        <origin xyz="${-caster_wheel_offset_x} ${-wheel_offset_y} ${caster_wheel_offset_z}" rpy="${pi/2} 0 0" />
        <axis xyz="0 0 -1"/>
    </joint>

    <link name="right_caster_wheel">
        <visual>
            <geometry>
                <cylinder radius="${caster_wheel_radius}" length="${caster_wheel_thickness}"/>
            </geometry>
            <material name="white"/>
        </visual>
        <collision>
            <geometry>
                <sphere radius="${caster_wheel_radius}"/>
            </geometry>
        </collision>
        <xacro:inertial_cylinder mass="${caster_wheel_mass}" length="${caster_wheel_thickness}" radius="${caster_wheel_radius}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_cylinder>
    </link>

    <gazebo reference="right_caster_wheel">
        <material>Gazebo/White</material>
        <mu1 value="0.001"/>
        <mu2 value="0.001"/>
    </gazebo>
</robot>